### ISSUE TITLE
Add slider for brain model alpha

### ISSUE THREAD

**Issue by VVander** [datastethoscope/code#22]
After including brain mesh into renderer, we should create a slider to change the opacity of the mesh.

**Comment by VVander** [comment]
UI element exists and basic test sphere model is being used right now. However, this can't be completed until Veena merges her work with mine since I don't know the exact composition of the CVL brain model.

**Comment by gswig** [comment]
This needs to be a priority so that we don’t have independent and non-overlapping streams of work
--
Gagan S Wig, PhD

University of Texas at Dallas
Assistant Professor, School of Behavioral and Brain Sciences

University of Texas Southwestern Medical Center
Adjunct Assistant Professor, Department of Psychiatry

Center for Vital Longevity
1600 Viceroy Drive, Suite 800
Dallas, TX 75235

Ph:  972 883 3731
Web: http://vitallongevity.utdallas.edu/cnl/
