### ISSUE TITLE
Bug: some UI elements stop working

### ISSUE THREAD

**Issue by VVander** [datastethoscope/code#42]
This is a major issue with Unity's UI system. Sliders will stop working if the render mode for the canvas they are on changes. More research will need to be done to resolve this, but it is an issue on Unity's end, not ours.

**Comment by VVander** [comment]
This is not able to be solved by us without getting Unity Technologies involved, which means waiting months for confirmation, reproducing, fixing, etc. if they will even acknowledge it as an issue at all since this is a very niche use case and I can't find other developers running into the same issue. 

Obviously this isn't a tenable solution for this project, so we are going to revert to using the system cursor instead in order to continue development for now. This will inhibit easy VR compatibility, but obviously this is a very low priority compared to a working UI. 

The other option is to remove the resolution independence features of the UI that were recently developed, as this would allow us to retain the VR compatible cursor for the UI. Based on previous discourse on the subject we are assuming that UI resolution independence is a greater need than VR compatibility (which will take some additional work regardless), so the system cursor will be our target. 

Using the system cursor instead requires some added development time since some features (namely, view selection) were implemented through use of the World Space Cursor and will need to be adjusted to use the system cursor instead. This work is documented here:

**Comment by gswig** [comment]
I'd like to hear more about the details for this

--
Gagan S Wig, PhD

University of Texas at Dallas
Assistant Professor, School of Behavioral and Brain Sciences

University of Texas Southwestern Medical Center
Adjunct Assistant Professor, Department of Psychiatry

Center for Vital Longevity
1600 Viceroy Drive, Suite 800<x-apple-data-detectors://2>
Dallas, TX 75235<x-apple-data-detectors://2>

Phone: 972 883 3731<tel:972%20883%203731>
Web:  http://vitallongevity.utdallas.edu/cnl/

On Nov 30, 2015, at 3:08 PM, Mike Leach <notifications@github.com<mailto:notifications@github.com>> wrote:


This is not able to be solved by us without getting Unity Technologies involved, which means waiting months for confirmation, reproducing, fixing, etc. if they will even acknowledge it as an issue at all since this is a very niche use case and I can't find other developers running into the same issue.

Obviously this isn't a tenable solution for this project, so we are going to revert to using the system cursor instead in order to continue development for now. This will inhibit easy VR compatibility, but obviously this is a very low priority compared to a working UI.

The other option is to remove the resolution independence features of the UI that were recently developed, as this would allow us to retain the VR compatible cursor for the UI. Based on previous discourse on the subject we are assuming that UI resolution independence is a greater need than VR compatibility (which will take some additional work regardless), so the system cursor will be our target.

Using the system cursor instead requires some added development time since some features (namely, view selection) were implemented through use of the World Space Cursor and will need to be adjusted to use the system cursor instead. This work is documented here:

**Comment by VVander** [comment]
I'll be happy to give some more thorough details about this when we meet.

**Comment by VVander** [comment]
I also edited the above comments to make them a little more clear.
